### PR TITLE
initialise Koin in shared code

### PR DESCRIPTION
**Pull request by joreilly**
Uses `KoinApplication` in shared CMP code to initialise Koin (cc @arnaudgiuliani)

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Great, thanks 👍

**Comment by zsmb13** [comment]
Does this API offer any specific benefits on top of making the code cleaner? I'm a little hesitant to merge this change because if users of this template need to add some platform-specific setup code (for example, to pass in a Room builder per platform), that will be more difficult for them to figure out without seeing the platform entry points.

**Comment by joreilly** [comment]
That's a fair point and this was just in case it was useful....mostly as you say to make code cleaner.  You do have option to pass iOS specific "stuff" in to `MainViewController` but perhaps means there isn't uniform way to do this if needed for other platforms as well.

**Comment by arnaudgiuliani** [comment]
I'm working on this topic now, trying to allow easier setup from Android. I'll propose you when it's ready.

**Pull request closed without merging**
